---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: crawler
    component: ui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: crawler
    component: ui
    release: {{ .Release.Name }}