---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    app: crawler
    component: rabbit-svc
spec:
  ports:
  - name: epmd
    port: 5672
  - name: amqp
    port: 4369
  - name: dist
    port: 5671
  - name: stats
    port: 25672
  selector:
    app: crawler
    component: rabbit