---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "bot.fullname" . }}
  labels:
    app: crawler
    component: bot
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: bot
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler-pod
      labels:
        app: crawler
        component: bot
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        env: 
        - name: MONGO
          value: {{ .Values.mongoHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: RMQ_HOST
          value: {{ .Values.rmqHost | default (printf "%s-rabbitmq" .Release.Name) }}
