---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bot.fullname" . }}
  labels:
    app: crawler
    component: bot
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 8000
  selector:
    app: crawler
    component: bot
    release: {{ .Release.Name }}